// <auto-generated />
using System;
using Deullam.Credit.Inquiry.Challenge.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Deullam.Credit.Inquiry.Challenge.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251219003658_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Deullam.Credit.Inquiry.Challenge.Domain.Features.GerenciarCredito.Credito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Aliquota")
                        .HasColumnType("DECIMAL(5, 2)")
                        .HasColumnName("aliquota");

                    b.Property<decimal>("BaseCalculo")
                        .HasColumnType("DECIMAL(15, 2)")
                        .HasColumnName("base_calculo");

                    b.Property<DateTime>("DataConstituicao")
                        .HasColumnType("DATE")
                        .HasColumnName("data_constituicao");

                    b.Property<string>("NumeroCredito")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_credito");

                    b.Property<string>("NumeroNfse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_nfse");

                    b.Property<bool>("SimplesNacional")
                        .HasColumnType("boolean")
                        .HasColumnName("simples_nacional");

                    b.Property<string>("TipoCredito")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_credito");

                    b.Property<decimal>("ValorDeducao")
                        .HasColumnType("DECIMAL(15, 2)")
                        .HasColumnName("valor_deducao");

                    b.Property<decimal>("ValorFaturado")
                        .HasColumnType("DECIMAL(15, 2)")
                        .HasColumnName("valor_faturado");

                    b.Property<decimal>("ValorIssqn")
                        .HasColumnType("DECIMAL(15, 2)")
                        .HasColumnName("valor_issqn");

                    b.HasKey("Id");

                    b.ToTable("credito", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Aliquota = 5.0m,
                            BaseCalculo = 25000.00m,
                            DataConstituicao = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroCredito = "123456",
                            NumeroNfse = "7891011",
                            SimplesNacional = true,
                            TipoCredito = "ISSQN",
                            ValorDeducao = 5000.00m,
                            ValorFaturado = 30000.00m,
                            ValorIssqn = 1500.75m
                        },
                        new
                        {
                            Id = 2L,
                            Aliquota = 4.5m,
                            BaseCalculo = 21000.00m,
                            DataConstituicao = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroCredito = "789012",
                            NumeroNfse = "7891011",
                            SimplesNacional = false,
                            TipoCredito = "ISSQN",
                            ValorDeducao = 4000.00m,
                            ValorFaturado = 25000.00m,
                            ValorIssqn = 1200.50m
                        },
                        new
                        {
                            Id = 3L,
                            Aliquota = 3.5m,
                            BaseCalculo = 17000.00m,
                            DataConstituicao = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroCredito = "654321",
                            NumeroNfse = "1122334",
                            SimplesNacional = true,
                            TipoCredito = "Outros",
                            ValorDeducao = 3000.00m,
                            ValorFaturado = 20000.00m,
                            ValorIssqn = 800.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
